## Import Libraries

In [98]:
# Importing libraries 
import pandas as pd
import numpy as np 
import os

## Import Hospital_General_Information and Hospital_Locations data sets

In [100]:
# Path Variable 
path = r'C:\Users\jmiel\JENNY_STUFF\MY_DOCS\CareerFoundry\U.S. Hospitals'

In [101]:
# Importing Hospital_General_Information os
hospital_general_information = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'Hospital_General_information.csv'), index_col = False)

In [102]:
# Importing Hospital_Locations os 
hospital_locations = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'hospital_locations.csv'), index_col = False)

## Check to ensure results of imported data

In [104]:
# check the information of the hospital_general_information
hospital_general_information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4818 entries, 0 to 4817
Data columns (total 30 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   index                                                          4818 non-null   int64
 1   Provider ID                                                    4818 non-null   int64
 2   Hospital Name                                                  4818 non-null   object
 3   Address                                                        4818 non-null   object
 4   City                                                           4818 non-null   object
 5   State                                                          4818 non-null   object
 6   ZIP Code                                                       4818 non-null   int64
 7   County Name                                                    4803 non-null   object
 8   Phone Number                                                   4818 non-null   int64
 9   Hospital Type                                                  4818 non-null   object
 10  Hospital Ownership                                             4818 non-null   object
 11  Emergency Services                                             4818 non-null   bool
 12  Meets criteria for meaningful use of EHRs                      0 non-null      float64
 13  Hospital overall rating                                        3648 non-null   float64
 14  Hospital overall rating footnote                               1342 non-null   object
 15  Mortality national comparison                                  4818 non-null   object
 16  Mortality national comparison footnote                         1337 non-null   object
 17  Safety of care national comparison                             4818 non-null   object
 18  Safety of care national comparison footnote                    1892 non-null   object
 19  Readmission national comparison                                4818 non-null   object
 20  Readmission national comparison footnote                       1002 non-null   object
 21  Patient experience national comparison                         4818 non-null   object
 22  Patient experience national comparison footnote                1355 non-null   object
 23  Effectiveness of care national comparison                      4818 non-null   object
 24  Effectiveness of care national comparison footnote             1116 non-null   object
 25  Timeliness of care national comparison                         4818 non-null   object
 26  Timeliness of care national comparison footnote                1331 non-null   object
 27  Efficient use of medical imaging national comparison           4818 non-null   object
 28  Efficient use of medical imaging national comparison footnote  2026 non-null   object
 29  Location                                                       4818 non-null   object
dtypes: bool(1), float64(2), int64(4), object(23)
memory usage: 1.1+ MB

While it appears the data imported effectively, there are some columns that need further analysis

In [106]:
# Check the information of hospital_locations dataset
hospital_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7623 entries, 0 to 7622
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       7623 non-null   int64
 1   X           7623 non-null   float64
 2   Y           7623 non-null   float64
 3   OBJECTID    7623 non-null   int64
 4   ID          7623 non-null   int64
 5   NAME        7623 non-null   object
 6   ADDRESS     7623 non-null   object
 7   CITY        7623 non-null   object
 8   STATE       7623 non-null   object
 9   ZIP         7623 non-null   int64
 10  ZIP4        7623 non-null   object
 11  TELEPHONE   7623 non-null   object
 12  TYPE        7623 non-null   object
 13  STATUS      7623 non-null   object
 14  POPULATION  7623 non-null   int64
 15  COUNTY      7623 non-null   object
 16  COUNTYFIPS  7623 non-null   object
 17  COUNTRY     7623 non-null   object
 18  LATITUDE    7623 non-null   float64
 19  LONGITUDE   7623 non-null   float64
 20  NAICS_CODE  7623 non-null   int64
 21  NAICS_DESC  7623 non-null   object
 22  SOURCE      7623 non-null   object
 23  SOURCEDATE  7623 non-null   object
 24  VAL_METHOD  7623 non-null   object
 25  VAL_DATE    7623 non-null   object
 26  WEBSITE     7623 non-null   object
 27  STATE_ID    7623 non-null   object
 28  ALT_NAME    7623 non-null   object
 29  ST_FIPS     7623 non-null   int64
 30  OWNER       7623 non-null   object
 31  TTL_STAFF   7623 non-null   int64
 32  BEDS        7623 non-null   int64
 33  TRAUMA      7623 non-null   object
 34  HELIPAD     7623 non-null   object
dtypes: float64(4), int64(9), object(22)
memory usage: 2.0+ MB

## Data Consistency Checks

#### hospital_general_information dataframe

In [109]:
# Rename columns to remove spacing to enhance formatting
hospital_general_information.rename(columns = {'Provider ID' : 'provider_id'}, inplace = True)
hospital_general_information.rename(columns = {'Hospital Name' : 'hospital_name'}, inplace = True)
hospital_general_information.rename(columns = {'Address' : 'address'}, inplace = True)
hospital_general_information.rename(columns = {'City' : 'city'}, inplace = True)
hospital_general_information.rename(columns = {'State' : 'state'}, inplace = True)
hospital_general_information.rename(columns = {'ZIP Code' : 'zip_code'}, inplace = True)
hospital_general_information.rename(columns = {'County Name' : 'county_name'}, inplace = True)
hospital_general_information.rename(columns = {'Phone Number' : 'phone_number'}, inplace = True)
hospital_general_information.rename(columns = {'Hospital Type' : 'hospital_type'}, inplace = True)
hospital_general_information.rename(columns = {'Hospital Ownership' : 'hospital_ownership'}, inplace = True)
hospital_general_information.rename(columns = {'Emergency Services' : 'emergency_services'}, inplace = True)
hospital_general_information.rename(columns = {'Meets criteria for meaningful use of EHRs' : 'meets_criteria_for_meaningful_use_of_ehrs'}, inplace = True)
hospital_general_information.rename(columns = {'Hospital overall rating' : 'hospital_overall_rating'}, inplace = True)
hospital_general_information.rename(columns = {'Hospital overall rating footnote' : 'hospital_overall_rating_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Mortality national comparison' : 'mortality_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Mortality national comparison footnote' : 'mortality_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Safety of care national comparison' : 'safety_of_care_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Safety of care national comparison footnote' : 'safety_of_care_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Readmission national comparison' : 'readmission_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Readmission national comparison footnote' : 'readmission_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Patient experience national comparison' : 'patient_experience_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Patient experience national comparison footnote' : 'patient_experience_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Effectiveness of care national comparison' : 'effectiveness_of_care_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Effectiveness of care national comparison footnote' : 'effectiveness_of_care_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Timeliness of care national comparison' : 'timeliness_of_care_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Timeliness of care national comparison footnote' : 'timeliness_of_care_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Efficient use of medical imaging national comparison' : 'efficient_use_of_medical_imaging_national_comparison'}, inplace = True)
hospital_general_information.rename(columns = {'Efficient use of medical imaging national comparison footnote' : 'efficient_use_of_medical_imaging_national_comparison_footnote'}, inplace = True)
hospital_general_information.rename(columns = {'Location' : 'location'}, inplace = True)

In [110]:
# Check the names of the newly renamed columns in dataframe
hospital_general_information.head()

,index,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,hospital_type,...,readmission_national_comparison_footnote,patient_experience_national_comparison,patient_experience_national_comparison_footnote,effectiveness_of_care_national_comparison,effectiveness_of_care_national_comparison_footnote,timeliness_of_care_national_comparison,timeliness_of_care_national_comparison_footnote,efficient_use_of_medical_imaging_national_comparison,efficient_use_of_medical_imaging_national_comparison_footnote,location
0,0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL 35957\n"
1,1,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL 36278\n"
2,2,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL 35801\n"
3,3,20001,PROVIDENCE ALASKA MEDICAL CENTER,BOX 196604,ANCHORAGE,AK,99508,ANCHORAGE,9072123675,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"BOX 196604\nANCHORAGE, AK 99508\n"
4,4,20018,YUKON KUSKOKWIM DELTA REG HOSPITAL,PO BOX 287,BETHEL,AK,99559,BETHEL,9075436300,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 287\nBETHEL, AK 99559\n"

In [111]:
# Check for missing values in hospital_general_information dataframe 
hospital_general_information.isnull().sum()

index                                                               0
provider_id                                                         0
hospital_name                                                       0
address                                                             0
city                                                                0
state                                                               0
zip_code                                                            0
county_name                                                        15
phone_number                                                        0
hospital_type                                                       0
hospital_ownership                                                  0
emergency_services                                                  0
meets_criteria_for_meaningful_use_of_ehrs                        4818
hospital_overall_rating                                          1170
hospital_overall_rating_footnote                                 3476
mortality_national_comparison                                       0
mortality_national_comparison_footnote                           3481
safety_of_care_national_comparison                                  0
safety_of_care_national_comparison_footnote                      2926
readmission_national_comparison                                     0
readmission_national_comparison_footnote                         3816
patient_experience_national_comparison                              0
patient_experience_national_comparison_footnote                  3463
effectiveness_of_care_national_comparison                           0
effectiveness_of_care_national_comparison_footnote               3702
timeliness_of_care_national_comparison                              0
timeliness_of_care_national_comparison_footnote                  3487
efficient_use_of_medical_imaging_national_comparison                0
efficient_use_of_medical_imaging_national_comparison_footnote    2792
location                                                            0
dtype: int64

There are a number of columns containing missing values requiring further analysis prior to addressing them

In [113]:
# Create a subset of the hospital_general_information to view missing values 
hospital_general_info_nan = hospital_general_information[hospital_general_information['county_name'].isnull() == True]

In [114]:
hospital_general_info_nan

,index,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,hospital_type,...,readmission_national_comparison_footnote,patient_experience_national_comparison,patient_experience_national_comparison_footnote,effectiveness_of_care_national_comparison,effectiveness_of_care_national_comparison_footnote,timeliness_of_care_national_comparison,timeliness_of_care_national_comparison_footnote,efficient_use_of_medical_imaging_national_comparison,efficient_use_of_medical_imaging_national_comparison_footnote,location
32,32,21301,PROVIDENCE VALDEZ MEDICAL CENTER,PO BOX 550,VALDEZ,AK,99686,NaN,9078352249,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 550\nVALDEZ, AK 99686\n"
33,33,21304,PETERSBURG MEDICAL CENTER,PO BOX 589,PETERSBURG,AK,99833,NaN,9077724291,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 589\nPETERSBURG, AK 99833\n"
34,34,21307,CORDOVA COMMUNITY MEDICAL CENTER,PO BOX 160 - 602 CHASE AVENUE,CORDOVA,AK,99574,NaN,9074248000,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 160 - 602 CHASE AVENUE\nCORDOVA, AK 995..."
217,217,430081,PHS INDIAN HOSPITAL AT PINE RIDGE,"HIGHWAY 18, MAIN ST., BLDG. 159",PINE RIDGE,SD,57770,NaN,6058675131,Acute Care Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"HIGHWAY 18, MAIN ST., BLDG. 159\nPINE RIDGE, S..."
218,218,480001,"ROY LESTER SCHNEIDER HOSPITAL,THE",9048 SUGAR ESTATE,ST THOMAS,VI,801,NaN,8097768311,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,"9048 SUGAR ESTATE\nST THOMAS, VI 00801\n"
279,279,640001,LBJ TROPICAL MEDICAL CENTER,FAGAALU VILLAGE,PAGO PAGO,AS,96799,NaN,6846334590,Acute Care Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"FAGAALU VILLAGE\nPAGO PAGO, AS 96799\n"
280,280,650001,GUAM MEMORIAL HOSPITAL AUTHORITY,85O GOV CARLOS G CAMACHO ROAD,TAMUNING,GU,96913,NaN,6716472552,Acute Care Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"85O GOV CARLOS G CAMACHO ROAD\nTAMUNING, GU 96..."
281,281,650003,GUAM REGIONAL MEDICAL CITY,133 ROUTE 3,DEDEDO,GU,96929,NaN,6716455500,Acute Care Hospitals,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"133 ROUTE 3\nDEDEDO, GU 96929\n"
282,282,660001,COMMONWEALTH HEALTH CENTER,"PO BOX 409CK, NAVY HILL ROAD",GARAPAN,MP,96950,NaN,6702348950,Acute Care Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 409CK, NAVY HILL ROAD\nGARAPAN, MP 96950\n"
646,646,21305,WRANGELL MEDICAL CENTER,310 BENNETT STREET PO BOX 1081,WRANGELL,AK,99929,NaN,9078747000,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"310 BENNETT STREET PO BOX 1081\nWRANGELL, AK 9..."
674,674,21312,SAMUEL SIMMONDS MEMORIAL HOSPITAL,7000 UULA ST,BARROW,AK,99723,NaN,9078524611,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"7000 UULA ST\nBARROW, AK 99723\n(71.298914, -1..."
778,778,20024,CENTRAL PENINSULA GENERAL HOSPITAL,250 HOSPITAL PLACE,SOLDOTNA,AK,99669,NaN,9072624404,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"250 HOSPITAL PLACE\nSOLDOTNA, AK 99669\n(60.49..."
807,807,21313,SOUTH PENINSULA HOSPITAL,4300 BARTLETT ST,HOMER,AK,99603,NaN,9072358101,Critical Access Hospitals,...,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"4300 BARTLETT ST\nHOMER, AK 99603\n(59.652133,..."
1082,1082,21302,PROVIDENCE SEWARD HOSPITAL,"417 FIRST AVENUE, PO BOX 365",SEWARD,AK,99664,NaN,9072245205,Critical Access Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"417 FIRST AVENUE, PO BOX 365\nSEWARD, AK 99664..."
3347,3347,480002,GOV JUAN F LUIS HOSPITAL & MEDICAL CTR,"#4007 EST DIAMOND RUBY, CHRISTIANSTED",ST CROIX,VI,820,NaN,3407786311,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"#4007 EST DIAMOND RUBY, CHRISTIANSTED\nST CROI..."

In [115]:
# Create a loc() fucntion stating if the county_name column contains  NaN, then state not available 
hospital_general_information.loc[hospital_general_information['county_name'].isna(), 'county_name'] = 'Not Available'

In [116]:
# Remove meets_criteria_for_meaningful_use_of_ehrs column as the entire column is blank and unnecessary for analysis 
hospital_general_information = hospital_general_information.drop(columns = ['meets_criteria_for_meaningful_use_of_ehrs'])

In [117]:
# validate that there are no longer any missing counts for the county_name column
hospital_general_information.isnull().sum()

index                                                               0
provider_id                                                         0
hospital_name                                                       0
address                                                             0
city                                                                0
state                                                               0
zip_code                                                            0
county_name                                                         0
phone_number                                                        0
hospital_type                                                       0
hospital_ownership                                                  0
emergency_services                                                  0
hospital_overall_rating                                          1170
hospital_overall_rating_footnote                                 3476
mortality_national_comparison                                       0
mortality_national_comparison_footnote                           3481
safety_of_care_national_comparison                                  0
safety_of_care_national_comparison_footnote                      2926
readmission_national_comparison                                     0
readmission_national_comparison_footnote                         3816
patient_experience_national_comparison                              0
patient_experience_national_comparison_footnote                  3463
effectiveness_of_care_national_comparison                           0
effectiveness_of_care_national_comparison_footnote               3702
timeliness_of_care_national_comparison                              0
timeliness_of_care_national_comparison_footnote                  3487
efficient_use_of_medical_imaging_national_comparison                0
efficient_use_of_medical_imaging_national_comparison_footnote    2792
location                                                            0
dtype: int64

In [118]:
# Check for duplicate values 
hospital_general_information_dups = hospital_general_information[hospital_general_information.duplicated()]

In [119]:
# Check new dataframe to determine if there are any duplicates
hospital_general_information_dups

Empty DataFrame
Columns: [index, provider_id, hospital_name, address, city, state, zip_code, county_name, phone_number, hospital_type, hospital_ownership, emergency_services, hospital_overall_rating, hospital_overall_rating_footnote, mortality_national_comparison, mortality_national_comparison_footnote, safety_of_care_national_comparison, safety_of_care_national_comparison_footnote, readmission_national_comparison, readmission_national_comparison_footnote, patient_experience_national_comparison, patient_experience_national_comparison_footnote, effectiveness_of_care_national_comparison, effectiveness_of_care_national_comparison_footnote, timeliness_of_care_national_comparison, timeliness_of_care_national_comparison_footnote, efficient_use_of_medical_imaging_national_comparison, efficient_use_of_medical_imaging_national_comparison_footnote, location]
Index: []

[0 rows x 29 columns]

There are no duplicates

In [140]:
# descriptive statistical analysis of hospital_general_information dataframe 
hospital_general_information[['hospital_overall_rating']].describe()

       hospital_overall_rating
count              3648.000000
mean                  3.073465
std                   0.834595
min                   1.000000
25%                   3.000000
50%                   3.000000
75%                   4.000000
max                   5.000000

#### hospital_locations dataframe

In [143]:
# Rename columns to adjust formatting 
hospital_locations.rename(columns = {'X' : 'x'}, inplace = True)
hospital_locations.rename(columns = {'Y' : 'y'}, inplace = True)
hospital_locations.rename(columns = {'OBJECTID' : 'object_id'}, inplace = True)
hospital_locations.rename(columns = {'ID' : 'id'}, inplace = True)
hospital_locations.rename(columns = {'NAME' : 'name'}, inplace = True)
hospital_locations.rename(columns = {'ADDRESS' : 'address'}, inplace = True)
hospital_locations.rename(columns = {'CITY' : 'city'}, inplace = True)
hospital_locations.rename(columns = {'STATE' : 'state'}, inplace = True)
hospital_locations.rename(columns = {'ZIP' : 'zip'}, inplace = True)
hospital_locations.rename(columns = {'ZIP4' : 'zip_4'}, inplace = True)
hospital_locations.rename(columns = {'TELEPHONE' : 'telephone'}, inplace = True)
hospital_locations.rename(columns = {'TYPE' : 'type'}, inplace = True)
hospital_locations.rename(columns = {'STATUS' : 'status'}, inplace = True)
hospital_locations.rename(columns = {'POPULATION' : 'population'}, inplace = True)
hospital_locations.rename(columns = {'COUNTY' : 'county'}, inplace = True)
hospital_locations.rename(columns = {'COUNTYFIPS' : 'county_fips'}, inplace = True)
hospital_locations.rename(columns = {'COUNTRY' : 'country'}, inplace = True)
hospital_locations.rename(columns = {'LATITUDE' : 'latitude'}, inplace = True)
hospital_locations.rename(columns = {'LONGITUDE' : 'longitude'}, inplace = True)
hospital_locations.rename(columns = {'NAICS_CODE' : 'naics_code'}, inplace = True)
hospital_locations.rename(columns = {'NAICS_DESC' : 'naics_desc'}, inplace = True)
hospital_locations.rename(columns = {'SOURCE' : 'source'}, inplace = True)
hospital_locations.rename(columns = {'SOURCEDATE' : 'source_date'}, inplace = True)
hospital_locations.rename(columns = {'VAL_METHOD' : 'val_method'}, inplace = True)
hospital_locations.rename(columns = {'VAL_DATE' : 'val_date'}, inplace = True)
hospital_locations.rename(columns = {'WEBSITE' : 'website'}, inplace = True)
hospital_locations.rename(columns = {'STATE_ID' : 'state_id'}, inplace = True)
hospital_locations.rename(columns = {'ALT_NAME' : 'alt_name'}, inplace = True)
hospital_locations.rename(columns = {'ST_FIPS' : 'st_fips'}, inplace = True)
hospital_locations.rename(columns = {'OWNER' : 'owner'}, inplace = True)
hospital_locations.rename(columns = {'TTL_STAFF' : 'ttl_staff'}, inplace = True)
hospital_locations.rename(columns = {'BEDS' : 'beds'}, inplace = True)
hospital_locations.rename(columns = {'TRAUMA' : 'trauma'}, inplace = True)
hospital_locations.rename(columns = {'HELIPAD' : 'helipad'}, inplace = True)

In [145]:
# Check the renamed column names 
hospital_locations.head()

,index,x,y,object_id,id,name,address,city,state,zip,...,val_date,website,state_id,alt_name,st_fips,owner,ttl_staff,beds,trauma,helipad
0,0,-1.322651e+07,4.049626e+06,2,53391362,LOS ROBLES HOSPITAL & MEDICAL CENTER - EAST CA...,150 VIA MERIDA,WESTLAKE VILAGE,CA,91362,...,2014/02/10 00:00:00+00,http://www.losrobleshospital.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,40,NOT AVAILABLE,N
1,1,-1.315620e+07,4.031978e+06,3,11190023,EAST LOS ANGELES DOCTORS HOSPITAL,4060 WHITTIER BOULEVARD,LOS ANGELES,CA,90023,...,2014/02/10 00:00:00+00,http://www.elalax.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,127,NOT AVAILABLE,N
2,2,-1.317190e+07,4.041752e+06,4,17090028,SOUTHERN CALIFORNIA HOSPITAL AT HOLLYWOOD,6245 DE LONGPRE AVENUE,HOLLYWOOD,CA,90028,...,2014/02/10 00:00:00+00,http://sch-hollywood.com/,NOT AVAILABLE,HOLLYWOOD COMMUNITY HOSPITAL OF HOLLYWOOD,6,PROPRIETARY,-999,100,NOT AVAILABLE,N
3,3,-1.313208e+07,4.037270e+06,5,23691706,KINDRED HOSPITAL BALDWIN PARK,14148 FRANCISQUITO AVENUE,BALDWIN PARK,CA,91706,...,2014/02/10 00:00:00+00,http://www.khbaldwinpark.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,95,NOT AVAILABLE,N
4,4,-1.315222e+07,4.009980e+06,6,25190712,LAKEWOOD REGIONAL MEDICAL CENTER,3700 EAST SOUTH STREET,LAKEWOOD,CA,90712,...,2014/02/10 00:00:00+00,http://www.lakewoodregional.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,172,NOT AVAILABLE,N

In [147]:
# check for missing values 
hospital_locations.isnull().sum()

index          0
x              0
y              0
object_id      0
id             0
name           0
address        0
city           0
state          0
zip            0
zip_4          0
telephone      0
type           0
status         0
population     0
county         0
county_fips    0
country        0
latitude       0
longitude      0
naics_code     0
naics_desc     0
source         0
source_date    0
val_method     0
val_date       0
website        0
state_id       0
alt_name       0
st_fips        0
owner          0
ttl_staff      0
beds           0
trauma         0
helipad        0
dtype: int64

There does not appear to be any missing values

In [150]:
# Check for duplicate values 
hospital_locations_dups = hospital_locations[hospital_locations.duplicated()]

In [152]:
# view results 
hospital_locations_dups

Empty DataFrame
Columns: [index, x, y, object_id, id, name, address, city, state, zip, zip_4, telephone, type, status, population, county, county_fips, country, latitude, longitude, naics_code, naics_desc, source, source_date, val_method, val_date, website, state_id, alt_name, st_fips, owner, ttl_staff, beds, trauma, helipad]
Index: []

[0 rows x 35 columns]

There are no duplicates

In [161]:
# Descriptive Statistics
hospital_locations[['ttl_staff', 'beds', 'population']].describe()

       ttl_staff         beds   population
count     7623.0  7623.000000  7623.000000
mean      -999.0    90.749705    90.749705
std          0.0   300.245366   300.245366
min       -999.0  -999.000000  -999.000000
25%       -999.0    25.000000    25.000000
50%       -999.0    70.000000    70.000000
75%       -999.0   184.000000   184.000000
max       -999.0  1592.000000  1592.000000

There appear to be abnormal numerical values in each column here as there can't be a negative value.

In [163]:
# replace -999 with NaN
hospital_locations.replace(-999, np.nan, inplace = True)

In [165]:
# Check to make sure values are now blank
hospital_locations.isnull().sum()

index             0
x                 0
y                 0
object_id         0
id                0
name              0
address           0
city              0
state             0
zip               0
zip_4             0
telephone         0
type              0
status            0
population      368
county            0
county_fips       0
country           0
latitude          0
longitude         0
naics_code        0
naics_desc        0
source            0
source_date       0
val_method        0
val_date          0
website           0
state_id          0
alt_name          0
st_fips           0
owner             0
ttl_staff      7623
beds            368
trauma            0
helipad           0
dtype: int64

## Export Dataframes

In [171]:
hospital_general_information.to_csv(os.path.join(path, 'Data','Prepared Data', 'Hospital_General_Information_Clean.csv'))

In [173]:
hospital_locations.to_csv(os.path.join(path, 'Data','Prepared Data', 'Hospital_Locations_Clean.csv'))